detectors:
  DuplicateMethodCall:
    allow_calls:
      - 'Rails.configuration'

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/controllers/concern":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/models/concern":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false

exclude_paths:
  - app/channels/application_cable/channel.rb
  - app/channels/application_cable/connection.rb
  - app/mailers/application_mailer.rb
  - app/models/application_record.rb
  - config/application.rb
  - test
  - db
